BSReview: Fixed bug where only a review on the mainpage could be edited
=> Manually cherry-picked I3aebed37d1e8d5a7f0426e4e4f5b278acbc96466
because of an unknowen error:
org.eclipse.jgit.errors.MissingObjectException: Missing unknown
a177cdabc7e83c30b71786f19e42055db873cfda

Change-Id: I8e0198fe134fcd7940fadf9eba9f3cad738da743